routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('login')->middleware('guest');
Auth::routes();

Route::get('/home','HomeController@index')->name('home')->middleware(['auth']);

Route::prefix('personas')->middleware(['auth'])->group(function (){

    Route::get('/','PersonController@list')->name('person.list');
    Route::get('/employee','PersonController@driverEnabledList')->name('person.driverEnabledList');
    Route::get('/{employee}','PersonController@show')->name('person.show');
    Route::post('/','PersonController@store')->name('person.store');
    Route::put('/{person}','PersonController@update')->name('person.update');
    Route::delete('/{person}','PersonController@delete')->name('person.delete');

    Route::prefix('employee')->group(function(){
        Route::get('/lista','PersonController@driversIndex')->name('person.list');

    });
    Route::prefix('clientes')->group(function(){
        Route::get('/lista','PersonController@clientsIndex')->name('client.index');
        Route::get('/lista-habilitados','PersonController@getEnabledClients')->name('client.listEnabled');

    });

});

Route::prefix('vehiculos')->middleware(['auth'])->group(function(){
    Route::get('/','CarController@index')->name('car.index');
    Route::get('/lista','CarController@listAll')->name('car.list');
    Route::get('/lista-en-servicio','CarController@listInService')->name('car.listInService');
    Route::post('/','CarController@store')->name('car.store');
    Route::delete('/{car}','CarController@delete')->name('car.delete');
    Route::post('/{car}/cambiar-servicio','CarController@changeService')->name('car.changeService');
    Route::put('/{car}','CarController@update')->name('car.update');


});

Route::prefix('registros')->middleware(['auth'])->group(function(){
    Route::get('/','RegisterCallController@index')->name('registerCall.index');
    Route::get('/lista-llamadas-solicitadas','RegisterCallController@listRequestedCalls')->name('registerCall.listRequestedCalls');
    Route::post('/asignar-vehiculo','RegisterCallController@assignCar')->name('registerCall.assignCar');
    Route::post('/terminar-servicio','RegisterCallController@endService')->name('registerCall.endService');
    Route::post('/guardar-registro','RegisterCallController@save')->name('registerCall.save');
    Route::get('/monitoreo','RegisterCallController@showListCallAssigned')->name('registerCall.showAssigned');
    Route::get('/lista-pedidos','RegisterCallController@listCallAssigned')->name('registerCall.assigned');
    Route::get('/historial','RegisterCallController@showListAllCall')->name('registerCall.showListAllCall');
    Route::get('/lista-historial','RegisterCallController@listAllCall')->name('registerCall.listAllCall');
    Route::put('/{register}','RegisterCallController@assignDestination')->name('registerCall.assignDestination');    

});

Route::prefix('tarifas')->middleware(['auth'])->group(function(){
    Route::get('/','RateController@index')->name('rate.index');
    Route::get('/lista','RateController@listAll')->name('rate.list');
    Route::post('/','RateController@store')->name('rate.store');
    Route::delete('/{rate}','RateController@destroy')->name('rate.delete');
    Route::put('/{rate}','RateController@update')->name('rate.update');
});


Route::Resource('user','UserController');
Route::prefix('user')->name('user.')->middleware(['auth'])->group(function(){
    Route::get('/list',"UserController@list")->name('list');
});

Route::prefix('usuarios')->middleware(['auth'])->group(function(){
    Route::get('/cambiar-password','Login2Controller@showResetPasswordForm')->name('user.reset_password');
    Route::put('/cambiar-password','Login2Controller@changePassword')->name('user.change_password');

});

resources/views/layouts/partials/navbar.blade.php
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="navbar-minimize">
            <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                <i class="material-icons visible-on-sidebar-mini">view_list</i>
            </button>
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"> @yield('title') </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">dashboard</i>
                        <p class="hidden-lg hidden-md">Dashboard</p>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">notifications</i>
                        <span class="notification">5</span>
                        <p class="hidden-lg hidden-md">
                            Notifications
                            <b class="caret"></b>
                        </p>
                    </a>
                    
                </li>
                <li>
                    <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">person</i>
                        <p class="hidden-lg hidden-md">Profile</p>
                    </a>
                </li>
                <li class="separator hidden-lg hidden-md"></li>
            </ul>
            <form class="navbar-form navbar-right" role="search">
                <div class="form-group form-search is-empty">
                    <input type="text" class="form-control" placeholder=" Buscar ">
                    <span class="material-input"></span>
                </div>
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                    <i class="material-icons">search</i>
                    <div class="ripple-container"></div>
                </button>
            </form>
        </div>
    </div>
</nav>

resources/views/layouts/partials/sidebar.blade.php
<div class="sidebar" data-active-color="rose" data-background-color="black" data-image="{{asset('img/sidebar-1.jpg')}}">
    <div class="logo">
        <a href="#" class="simple-text logo-mini">
            PF
        </a>
        <a href="#" class="simple-text logo-normal">
            Panificadora
        </a>
    </div>
    <div class="sidebar-wrapper">
        <div class="user">
            <div class="photo">
                <img src="{{asset('img/faces/avatar.jpg')}}" />

            </div>
            <div class="info">
                <a data-toggle="collapse" href="#collapseSesion" class="collapsed">
                    <span>
                        <span>{{Auth::check()?Auth::user()->username:'0'}}</span>
                        <b class="caret"></b>
                    </span>
                </a>
                <div class="clearfix"></div>
                <div class="collapse" id="collapseSesion">
                    <ul class="nav">
                        <li>
                            <a href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                           document.getElementById('logout-form').submit();">
                                <span class="sidebar-mini"> EP </span>
                                <span class="sidebar-normal"> Cerrar Sesión </span>
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                        <li>
                            <a href="{{ route('user.reset_password') }}">
                                <span class="sidebar-mini"> CP </span>
                                <span class="sidebar-normal"> Cambiar password </span>
                            </a>
                        </li>

                        
                    </ul>
                </div>
            </div>
        </div>
        <ul class="nav">
            <li class="nav-item ">
                <a class="nav-link collapsed" data-toggle="collapse" href="#mapsAlmacen" aria-expanded="false">
                    <i class="material-icons">inventory_2</i>
                    <p> Almacen
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="mapsAlmacen">
                    <ul class="nav">
                        <li class="nav-ite">
                            <a class="nav-link" href="../examples/maps/google.html">
                                <span class="sidebar-mini"> Mov </span>
                                <span class="sidebar-normal"> Movimientos </span>
                            </a>
                        </li>
                        <li class="nav-ite">
                            <a class="nav-link" href="../examples/maps/fullscreen.html">
                                <span class="sidebar-mini"> Rep </span>
                                <span class="sidebar-normal"> Reportes</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item ">
                <a class="nav-link collapsed" data-toggle="collapse" href="#mapsProduccion" aria-expanded="false">
                    <i class="material-icons">build</i>
                    <p> Produccion
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="mapsProduccion" style="">
                    <ul class="nav">
                        <li class="nav-item ">
                            <a class="nav-link" href="../examples/maps/google.html">
                                <span class="sidebar-mini"> Reg </span>
                                <span class="sidebar-normal"> Registros </span>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="../examples/maps/fullscreen.html">
                                <span class="sidebar-mini"> Rep </span>
                                <span class="sidebar-normal"> Reportes</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item ">
                <a class="nav-link collapsed" data-toggle="collapse" href="#mapsVentas" aria-expanded="false">
                    <i class="material-icons">shopping_cart</i>
                    <p> Ventas
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="mapsVentas" style="">
                    <ul class="nav">
                        <li class="{{request()->is('*/conductores/*')?'active':''}}">
                            <a href="{{route('driver.index')}}">
                                <i class="material-icons">rowing</i>
                                <p> Clientes </p>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="../examples/maps/google.html">
                                <span class="sidebar-mini"> Reg </span>
                                <span class="sidebar-normal"> Registros </span>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="../examples/maps/fullscreen.html">
                                <span class="sidebar-mini"> Rep </span>
                                <span class="sidebar-normal"> Reportes</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item ">
                <a class="nav-link collapsed" data-toggle="collapse" href="#mapsDespachos" aria-expanded="false">
                    <i class="material-icons">grid_on</i>
                    <p> Despachos
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="mapsDespachos" style="">
                    <ul class="nav">
                        <li class="{{request()->is('*/conductores/*')?'active':''}}">
                            <a href="{{route('driver.index')}}">
                                <i class="material-icons">rowing</i>
                                <p> Despachos </p>
                            </a>
                        </li>
                        <li class="{{request()->is('vehiculos')?'active':''}}">
                            <a href="{{route('car.index')}}">
                                <i class="material-icons">directions_car</i>
                                <p> Vehículos </p>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="../examples/maps/fullscreen.html">
                                <span class="sidebar-mini"> Rep </span>
                                <span class="sidebar-normal"> Reportes</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item ">
                <a class="nav-link collapsed" data-toggle="collapse" href="#mapsConfig" aria-expanded="false">
                    <i class="material-icons">settings</i>
                    <p> Configuracion
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="mapsConfig">
                    <ul class="nav">
                        <li class="{{request()->is('*/employee/*')?'active':''}}">
                            <a href="{{route('driver.index')}}">
                                <i class="material-icons">people</i>
                                <p> Empleados </p>
                            </a>
                        </li>
                        <li class="{{request()->is('*/user/*')?'active':''}}">
                            <a href="{{route('user.index')}}">
                                <i class="material-icons">rowing</i>
                                <p> Usuarios </p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            {{--<li class="{{request()->is('registros')?'active':''}}">--}}
                {{--<a href="{{route('registerCall.index')}}">--}}
                    {{--<i class="material-icons">edit</i>--}}
                    {{--<p> Registro </p>--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li class="{{request()->is('*/monitoreo')?'active':''}}">--}}
                {{--<a href="{{route('registerCall.showAssigned')}}">--}}
                    {{--<i class="material-icons">departure_board</i>--}}
                    {{--<p> Monitoreo </p>--}}
                {{--</a>--}}
            {{--</li>--}}
            {{----}}
            {{--<li class="{{request()->is('tarifas')?'active':''}}">--}}
                {{--<a href="{{route('rate.index')}}">--}}
                    {{--<i class="material-icons">directions_car</i>--}}
                    {{--<p> Tarifas </p>--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li class="{{request()->is('*/clientes/*')?'active':''}}">--}}
                {{--<a href="{{route('client.index')}}">--}}
                    {{--<i class="material-icons">today</i>--}}
                    {{--<p> Agenda </p>--}}
                {{--</a>--}}
            {{--</li>--}}


            {{--<li class="{{request()->is('*/historial')?'active':''}}">--}}
                {{--<a href="{{route('registerCall.showListAllCall')}}">--}}
                    {{--<i class="material-icons">directions_car</i>--}}
                    {{--<p> Usuarios </p>--}}
                {{--</a>--}}
            {{--</li>--}}

           

        </ul>
    </div>
</div>